In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random

In [2]:
class perceptron:
  def __init__(self,eta,epochs):
    self.weights = np.random.randn(3)*1e-4
    print(f"initial weights before training : \n{self.weights}")
    self.eta = eta
    self.epochs = epochs


  def activationFunction(self,inputs,weights):
    z = np.dot(inputs,weights)
    return np.where(z>0,1,0)

  def fit(self,X,y):
    self.X = X
    self.y = y
    X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
    print(f"X with bias : \n{X_with_bias}")

    for epoch in range(self.epochs):
      print("--"*10)
      print(f"for epoch >> {epoch}")
      print("--"*10)
      y_hat = self.activationFunction(X_with_bias,self.weights)
      print(f"predicted value after forward pass : \n{y_hat}")
      self.error = self.y - y_hat
      print(f"error : \n{self.error}")
      self.weights = self.weights + self.eta * np.dot(X_with_bias.T,self.error)
      print(f"updated weights after epoch : {epoch}/{self.epochs} : \n{self.weights}")
      print("##"*10)

  def predict(self,X):
    x_with_bias = np.c_[X, -np.ones((len(X),1))]
    return self.activationFunction(x_with_bias,self.weights)

In [3]:
AND = {
    'x1' : [0,0,1,1],
    'x2' : [0,1,0,1],
    'y' : [0,0,0,1]
}
AND = pd.DataFrame(AND)
AND

,x1,x2,y
0,0,0,0
1,0,1,0
2,1,0,0
3,1,1,1


In [4]:
X_and = AND.drop('y',axis=1)
y_and= AND['y']


In [5]:
model_and = perceptron(eta = 0.5, epochs=5)
model_and.fit(X_and,y_and)

initial weights before training : 
[ 1.47082971e-04 -3.29604246e-05 -3.54267015e-07]
X with bias : 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 0
--------------------
predicted value after forward pass : 
[1 0 1 1]
error : 
0   -1
1    0
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch : 0/5 : 
[-4.99852917e-01 -3.29604246e-05  9.99999646e-01]
####################
--------------------
for epoch >> 1
--------------------
predicted value after forward pass : 
[0 0 0 0]
error : 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch : 1/5 : 
[1.47082971e-04 4.99967040e-01 4.99999646e-01]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass : 
[0 0 0 1]
error : 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch : 2/5 : 
[1.47082971e-04 4.99967040e-01 4.99999646e-01]
####################
--------------------
for epoc

In [6]:
OR = {
    'x1' : [0,0,1,1],
    'x2' : [0,1,0,1],
    'y' : [0,1,1,1]
}
OR = pd.DataFrame(OR)
OR


,x1,x2,y
0,0,0,0
1,0,1,1
2,1,0,1
3,1,1,1


In [7]:
X_or = OR.drop('y',axis=1)
y_or= OR['y']

In [9]:
model_or = perceptron(eta = 0.5, epochs=10)
model_or.fit(X_or,y_or)

initial weights before training : 
[-1.06449793e-04 -1.94589454e-05  1.30048004e-04]
X with bias : 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 0
--------------------
predicted value after forward pass : 
[0 0 0 0]
error : 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epoch : 0/10 : 
[ 0.99989355  0.99998054 -1.49986995]
####################
--------------------
for epoch >> 1
--------------------
predicted value after forward pass : 
[1 1 1 1]
error : 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch : 1/10 : 
[ 0.99989355  0.99998054 -0.99986995]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass : 
[1 1 1 1]
error : 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch : 2/10 : 
[ 0.99989355  0.99998054 -0.49986995]
####################
--------------------
for epoch >> 3
--------------------

# Single Layer perceptron doesnt work on XOR logic

In [10]:
XOR = {
    'x1' : [0,0,1,1],
    'x2' : [0,1,0,1],
    'y' : [0,1,1,0]
}
XOR = pd.DataFrame(XOR)
XOR


,x1,x2,y
0,0,0,0
1,0,1,1
2,1,0,1
3,1,1,0


In [11]:
X_xor = XOR.drop('y',axis=1)
y_xor= XOR['y']

In [12]:
model_xor = perceptron(eta = 0.5, epochs=10)
model_xor.fit(X_xor,y_xor)

initial weights before training : 
[1.57115289e-04 1.76904032e-05 7.37047982e-05]
X with bias : 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 0
--------------------
predicted value after forward pass : 
[0 0 1 1]
error : 
0    0
1    1
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch : 0/10 : 
[-4.99842885e-01  1.76904032e-05  7.37047982e-05]
####################
--------------------
for epoch >> 1
--------------------
predicted value after forward pass : 
[0 0 0 0]
error : 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch : 1/10 : 
[ 1.57115289e-04  5.00017690e-01 -9.99926295e-01]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass : 
[1 1 1 1]
error : 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch : 2/10 : 
[-4.99842885e-01  1.76904032e-05  7.37047982e-05]
####################
--------------------
fo